### ISSUE TITLE
issue:

### ISSUE THREAD

**Issue by harshitethic** [MR-RIKI/windows11-VPS#1]
chmod: cannot access 'azurewinvmplus': No such file or directory
bash: ./azurewinvmplus: No such file or directory

**Comment by playconta4** [comment]
> chmod: cannot access 'azurewinvmplus': No such file or directory bash: ./azurewinvmplus: No such file or directory

`curl -skLO https://is.gd/oxs0bJ ; chmod +x oxs0bJ ; ./oxs0bJ `

Notice this change, but now I get the error:

```
/tmp/tmp.QvaUTiuSrg/az-create-plus.sh: line 1: 404:: command not found
```

**Comment by MR-RIKI** [comment]
You Can Genarete The Raw link directly from this repo

**Comment by forodo** [comment]
> You Can Genarete The Raw link directly from this repo

please guide me
How to make raw link?
